### ISSUE TITLE
Add check - date picker not appearing

### ISSUE THREAD

**Issue by tech4bueno** [MuffinTheDragon/daily-habit-tracker#2]
The date picker for the "Add check" functionality does not open, except for habits where all days are disabled - at least on Safari 17.5 (not tested on other browsers).

**Comment by MuffinTheDragon** [comment]
That date picker will enable days that meet the following criteria:

1. date is after when habit was created
2. date hasn't been checked yet (either through checkbox or retroactively using the "add check")
3. date is before today

**Comment by tech4bueno** [comment]
I probably didn't explain very well. The date picker does not appear at all. See below:

![datepicker](https://github.com/MuffinTheDragon/daily-habit-tracker/assets/164949278/b95fbda9-fbbc-410e-9fcf-b4b895fcedf7)

**Comment by MuffinTheDragon** [comment]
Thanks for this, seems like a weird interaction on iOS with the calendar component. But it should be fixed now

**Comment by tech4bueno** [comment]
Working great now! Nice job, and thankyou 😄
