### ISSUE TITLE
Time travel

### ISSUE THREAD

**Issue by tech4bueno** [MuffinTheDragon/daily-habit-tracker#3]
Something funky is going on with the commit dates in this repo 😁

<img width="463" alt="Screenshot 2024-07-10 at 15 48 17" src="https://github.com/MuffinTheDragon/daily-habit-tracker/assets/164949278/4bee7613-d22f-4e79-b2ef-b9c7cdd86e8a">

**Comment by MuffinTheDragon** [comment]
_awkward_ so I was testing some cases when switching to different years, and I accidently committed without resetting the date. Didn't realize this was even possible

**Comment by tech4bueno** [comment]
Damn, I thought you had invented a time machine and were going to share the secret with us 😆
