### ISSUE TITLE
hide completed habits for the day

### ISSUE THREAD

**Issue by DavoSculdun** [MuffinTheDragon/daily-habit-tracker#4]
Is there a way completed habits for the day can be automatically hidden?

**Comment by MuffinTheDragon** [comment]
Not currently, I can look into maybe putting completed habits inside some collapsible section at the bottom

**Comment by MuffinTheDragon** [comment]
Pushed out collapsible sections for completed and archived habits

**Comment by MuffinTheDragon** [comment]
Marking this as complete
