### ISSUE TITLE
Error when opening graph

### ISSUE THREAD

**Issue by tech4bueno** [MuffinTheDragon/daily-habit-tracker#5]
Recent changes to the pause storage logic appear to have broken the graph for existing users:

![pausechanges](https://github.com/user-attachments/assets/263f60ed-c9f1-4c23-916f-de4e51a52669)

`TypeError: undefined is not an object (evaluating 'e.getFullYear')`

<img width="202" alt="Screenshot 2024-07-11 at 21 42 04" src="https://github.com/user-attachments/assets/66fd49aa-ac75-4b52-a787-3f05dbfe007c">

**Comment by MuffinTheDragon** [comment]
I migrated everyone's data to support the new format. I guess if someone didn't sync their data, the model wouldn't be able to update. If you delete your indexed db, it should work

I'll need to look into upgrading older versions

**Comment by tech4bueno** [comment]
Yes - offline user here. No big deal to nuke the DB for now. Probably won't want to do lose my history next time though 😄

**Comment by MuffinTheDragon** [comment]
I do have a hotfix for this that I can push out (might not be of much help if you already reset your db)

**Comment by tech4bueno** [comment]
Legend. Thanks!
